name: denoising-autoencoder
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - keras
  - opencv
  - pillow
  - ipykernel
  - pip
  - tensorflow  
  - pip:
      - theano-pymc
