name: project3
dependencies:
  - python==3.9
  - pandas
  - numpy
  - matplotlib
  - Keras
  - opencv
  - seaborn
  - scikit-learn
  - theano
  - pillow
  - ipykernel
  - jupyter
  - pip:
    - piexif
    - keras
    - tensorflow
    - opencv-python