name: denoising-autoencoder
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - numpy
  - matplotlib
  - Keras
  - opencv
  - seaborn
  - scikit-learn
  - pillow
  - ipykernel
  - jupyter
  - pip
  - pip:
    - piexif
    - keras
    - tensorflow
    - opencv-python
    - theano
